### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#320]
- Update source headers to use new branding
- Update Doxygen comments to use new style
- (done) Change all flecsi includes to use angle brackets
- Fix type names to match style conventions
- (done)  Replace header guards with #pragma once
- Rename template parameters to be descriptive
- Run clang-format `clang-format -i -style=file *.h` (for example)

Sub-directory assignments:

Nick: topology, concurrency, data
Irina: execution, utils, coloring

**Comment by cmsquared** [comment]
Is the `#pragma once` thing a standard?  @cferenba was looking into this and had some concerns with some compilers

**Comment by timmah** [comment]
Not ISO c++ standard. I think @cferenba was satisfied that it's not an issue (until it is).

**Comment by cferenba** [comment]
I did a ridiculous amount of research on this question a few weeks ago.

`#pragma once` is not part of the ISO standard.  It has been considered and rejected, because there are a few unusual use cases where it cannot be implemented in any reasonable way.
Most current compilers in common use do provide it, according to https://en.wikipedia.org/wiki/Pragma_once#Portability . The only outlier that might affect us in the short term is PGI; I did some testing and PGI 16.10 apparently does provide it, although it is undocumented.

All that to say, it is probably safe for us to continue using `#pragma once` even though it is not standard.  It is conceivable that in future we might need to support some bleeding-edge hardware with a toolchain that does not, and perhaps cannot, provide it.  If that should happen, there are tools out there that will go through a source tree and automatically convert all occurrences of `#pragma once` to conventional `#include` guards.
