### ISSUE TITLE
hash can alias fid causing [error 356] LEGION ERROR: Aliased and interfering region requirements for individual tasks are not permitted.

### ISSUE THREAD

**Issue by jpietarilagraham** [laristra/flecsi#455]
I have a reproducer available on request, but basically what I see is that these two sets of names:

Sl_a_avsdr, // fid = 296
Sl_a_anidr,
Sl_a_avsdf,
Sl_a_anidf,

and

Sx_a_avsdr,
Sx_a_anidr,
Sx_a_avsdf, // fid = 296
Sx_a_anidf,

give only 4 different hash values (instead of 8) between them.  This will be not fun for a non-flecsi-core developer to debug when it happens to them.

**Comment by tuxfan** [comment]
We should investigate different hashing algorithms, or try to split data into finer-grained bins.

**Comment by staleyLANL** [comment]
On it. There will always be more possible strings than there are integer hashes! However, something like what the OP described just shouldn't happen so easily. We should also see if there's a good way to have the code detect and gracefully report an aliased fid in the unlikely event that it still happens, instead of sending users hunting for the source of some consequental error.

**Comment by staleyLANL** [comment]
```

// Reproducer

#include "const_string.h"
#include <iostream>
#include <map>

// try2hash
template<std::size_t N>
void try2hash(const char (&str)[N])
{
   const std::size_t hash = flecsi::utils::const_string_t(str).hash();
   std::cout << hash << " ==> \"" << str << '"';

   static std::map<std::size_t,std::string> map;
   const auto pair = map.insert(std::pair<std::size_t,std::string>(hash,str));

   if (!pair.second) {
      if (str == pair.first->second)
         std::cout << " as before";
      else
         std::cout << " REJECTED; duplicates hash of \""
                   << pair.first->second << '"';
   }
   std::cout << std::endl;
}

// driver
namespace flecsi {
namespace execution {
   void driver(int, char **)
   {
      try2hash("foo");
      try2hash("foo"); // dup expected
      try2hash("foo"); // dup expected

      try2hash("Sl_a_avsdr");
      try2hash("Sl_a_anidr");
      try2hash("Sl_a_avsdf");
      try2hash("Sl_a_anidf");

      try2hash("Sx_a_avsdr"); // dup is not OK!
      try2hash("Sx_a_anidr"); // ...
      try2hash("Sx_a_avsdf"); // ...
      try2hash("Sx_a_anidf"); // ...
   }
}
}

```

**Comment by staleyLANL** [comment]
Looking at string_hash_u() (formerly string_hash__()) in hash.h, it seems that it's doing little more than shifting the input string's characters by multiples of 8, and bitwise-or'ing into an output integral (probably 64-bit std::size_t) value. It turns out that, for example, the following two strings hash to the same result:

     "22345678a"  // 2...a
     "12345678b"  // 1...b

and ditto for the following two:

     "22345678b"  // 2...b
     "12345678a"  // 1...a

In both cases, the middle characters stay the same, while the first and last change simultaneously. Ideally, a hash function will tend to produce entirely different hashes for "close" inputs.

**Comment by staleyLANL** [comment]
Here's what I believe will work much better. I based this on some online reading about hash functions. We can probably improve this even further, but, for the moment, I believe this will produce better hashes (with fewer collisions) than the present code does. Note that C++14 and C++17 no longer require that a constexpr function has only a return statement. The following should be entirely good as constexpr, so that its output from compile-time inputs is still compile-time. I'll integrate this into hash.h's string_hash_u() function.

```
// hash
template<class INTEGER, class STRING>
inline constexpr INTEGER hash(STRING &&str, const std::size_t n)
{
   // String-to-integer hash function, based on prime numbers.
   // References:
   //    https://stackoverflow.com/questions/8317508/hash-function-for-a-string
   //    https://planetmath.org/goodhashtableprimes

   const INTEGER P = 3145739; // prime
   const INTEGER Q = 6291469; // prime, a bit less than twice the first one

   INTEGER h = 37; // prime
   INTEGER i = 0;
   while (i < n)
      h = (h * P) ^ (str[i++] * Q);
   return h;
}
```

**Comment by jlippuner** [comment]
This is great! It looks like there are also constexpr version of the very commonly used SHA256 hash function: https://github.com/aguinet/sha256_literal

**Comment by staleyLANL** [comment]
Done, and with updated tests.
